// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk9wV17k0LwPDuWOTrmcZDDv_PTdj7yyA',
    appId: '1:15777884952:web:de87d8fe2ea848f5e04c6d',
    messagingSenderId: '15777884952',
    projectId: 'my-notes-project-b7fc4',
    authDomain: 'my-notes-project-b7fc4.firebaseapp.com',
    storageBucket: 'my-notes-project-b7fc4.appspot.com',
    measurementId: 'G-ZTTFZFDVGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzGshBxHNPQ6wfDf2nRPN93sZxqqGH6-w',
    appId: '1:15777884952:android:2000e39b19bcfbdde04c6d',
    messagingSenderId: '15777884952',
    projectId: 'my-notes-project-b7fc4',
    storageBucket: 'my-notes-project-b7fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NB4RmwRwF8ay6v6K1y5GKS4GJZAdXqA',
    appId: '1:15777884952:ios:4e0234efff178f82e04c6d',
    messagingSenderId: '15777884952',
    projectId: 'my-notes-project-b7fc4',
    storageBucket: 'my-notes-project-b7fc4.appspot.com',
    iosClientId: '15777884952-aocd88sa3euku58n00d8k1voo10h9hgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearnProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NB4RmwRwF8ay6v6K1y5GKS4GJZAdXqA',
    appId: '1:15777884952:ios:4e0234efff178f82e04c6d',
    messagingSenderId: '15777884952',
    projectId: 'my-notes-project-b7fc4',
    storageBucket: 'my-notes-project-b7fc4.appspot.com',
    iosClientId: '15777884952-aocd88sa3euku58n00d8k1voo10h9hgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearnProject',
  );
}
